const ADMIN_EMAIL="v.antonyuk95@gmail.com";
const $=id=>document.getElementById(id);
let authMode="login",session=null,profile=null,projects=[],current=null,active=null,drag=null,off={x:0,y:0};
const screens=["login","pending","projects","project","admin"].map($);
function show(s){screens.forEach(x=>x.classList.add("hidden"));$(s).classList.remove("hidden")}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),2500)}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16)}
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function dstr(d){return new Date(d).toISOString().slice(0,10)}
function fmt(d){return d?new Date(d).toLocaleString("cs-CZ",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):""}
function color(c){return c=="green"?"var(--g)":c=="orange"?"var(--o)":c=="blue"?"#60a5fa":c=="gray"?"#94a3b8":"var(--r)"}
function approvalColor(a={}){let n=["karel","ivca","vlada"].filter(p=>a[p]).length;return n==3?"green":n>=1?"orange":"red"}

$("tabLogin").onclick=()=>setMode("login");$("tabRegister").onclick=()=>setMode("register");
function setMode(m){authMode=m;$("tabLogin").classList.toggle("active",m=="login");$("tabRegister").classList.toggle("active",m=="register");$("authBtn").textContent=m=="login"?"Přihlásit":"Registrovat";$("msg").textContent=""}
$("authBtn").onclick=async()=>{let email=$("email").value.trim().toLowerCase(),password=$("password").value;if(!email||!password)return $("msg").textContent="Vyplň email a heslo.";try{$("authBtn").disabled=true;if(authMode=="login"){let {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;await init()}else{let {error}=await supabaseClient.auth.signUp({email,password});if(error)throw error;$("msg").textContent="Registrace uložena. Účet čeká na schválení adminem.";setMode("login")}}catch(e){$("msg").textContent=e.message||"Chyba"}finally{$("authBtn").disabled=false}}
async function init(){let {data}=await supabaseClient.auth.getSession();session=data.session;if(!session)return show("login");let {data:p,error}=await supabaseClient.from("profiles").select("*").eq("id",session.user.id).maybeSingle();if(error||!p)return show("pending");profile=p;if(p.status!="approved")return show("pending");$("adminBtn").classList.toggle("hidden",p.role!="admin");await loadProjects();renderProjects();show("projects")}
async function loadProjects(){let {data,error}=await supabaseClient.from("projects").select("*").order("updated_at",{ascending:false});projects=error?[]:(data||[]);if(error)toast("Nepodařilo se načíst projekty")}
function meta(p){let d=p.data||{};if(p.type=="timeline"){let r=d.rows?.length||0,i=(d.rows||[]).reduce((s,x)=>s+(x.items||[]).length,0);return `${r} řádků · ${i} položek<br>Klikni pro otevření projektu`}if(p.type=="notesCalendar")return `${d.notes?.length||0} poznámek<br>Klikni pro otevření projektu`;return `${d.nodes?.length||0} karet · ${d.edges?.length||0} propojení<br>Klikni pro otevření projektu`}
function renderProjects(){["listImageMap","listPavojk","listTimeline","listCalendar"].forEach(id=>$(id).innerHTML="");let map={imageMap:"listImageMap",pavojk:"listPavojk",timeline:"listTimeline",notesCalendar:"listCalendar"};projects.forEach(p=>{let b=document.createElement("button");b.className="projectCard";b.innerHTML=`<h3>${esc(p.name)}</h3><p>${meta(p)}</p>`;b.onclick=()=>openProject(p.id);$(map[p.type]||"listImageMap").appendChild(b)})}
function defaultData(type){if(type=="timeline"){let t=new Date();return{start:dstr(t),days:Math.ceil((new Date(t.getFullYear(),11,31)-t)/86400000)+1,rows:[1,2,3].map(_=>({id:uid(),name:"Nový řádek",items:[]}))}}if(type=="notesCalendar"){let t=new Date();return{year:t.getFullYear(),month:t.getMonth(),notes:[],dayDetails:{}}}return{nodes:[{id:uid(),title:type=="pavojk"?"Nová buňka":"Homepage",x:1000,y:520,detail:"",detailImages:[],notes:[],approvals:{karel:false,ivca:false,vlada:false},titleColor:type=="pavojk"?"orange":"red"}],edges:[]}}
async function createProject(type,name){let {data,error}=await supabaseClient.from("projects").insert({name,type,data:defaultData(type)}).select().single();if(error)return toast("Projekt se nepodařilo vytvořit");projects.unshift(data);$("typeModal").classList.add("hidden");openProject(data.id)}
async function openProject(id){current=projects.find(p=>p.id==id);if(!current)return toast("Projekt nenalezen");$("projectName").textContent=current.name;show("project");renderWork()}
async function save(){if(!current)return;current.updated_at=new Date().toISOString();let {error}=await supabaseClient.from("projects").update({name:current.name,data:current.data,updated_at:current.updated_at}).eq("id",current.id);if(error)console.warn(error)}
function renderWork(){$("canvas").innerHTML="";$("svg").innerHTML="";if(current.type=="timeline")return renderTimeline();if(current.type=="notesCalendar")return renderCalendar();renderMap()}
function ensure(){current.data=current.data||{};current.data.nodes=current.data.nodes||[];current.data.edges=current.data.edges||[];return current.data}
function renderMap(){let data=ensure();data.nodes.forEach(n=>{let el=document.createElement("div");el.className="node";el.style.left=n.x+"px";el.style.top=n.y+"px";let bg=current.type=="imageMap"?approvalColor(n.approvals):(n.titleColor||"orange");el.innerHTML=`<div class="head" style="background:${color(bg)}"><h3 contenteditable>${esc(n.title||"Nová buňka")}</h3>${current.type=="imageMap"?`<button class="round apprBtn">👍</button>`:""}<button class="round noteBtn ${n.notes?.length?"has":""}" data-count="${n.notes?.length||0}">💡</button><button class="round del">×</button></div>${current.type=="imageMap"?`<div class="imgArea">${n.imageUrl?`<img src="${n.imageUrl}">`:"<span>Zatím není nahraný obrázek<br>Klikni na „Nahrát“</span>"}</div>`:""}<div class="body"><input class="short" placeholder="Detail / krátký popis" value="${esc(n.short||"")}"><div class="actions">${current.type=="imageMap"?`<label class="file">Nahrát<input class="nodeFile" type="file" accept="image/*" hidden></label>`:`<button class="openDetail">Detail</button>`}<button class="openDetail">Detail obrázku</button></div></div><button class="addChild">+</button>`;$("canvas").appendChild(el);attachNode(el,n)});renderEdges()}
function renderEdges(){let d=ensure();$("svg").innerHTML="";d.edges.forEach(e=>{let a=d.nodes.find(n=>n.id==e.from),b=d.nodes.find(n=>n.id==e.to);if(!a||!b)return;let p=document.createElementNS("http://www.w3.org/2000/svg","path"),x1=a.x+320,y1=a.y+110,x2=b.x,y2=b.y+110,m=(x1+x2)/2;p.setAttribute("d",`M${x1} ${y1} C${m} ${y1},${m} ${y2},${x2} ${y2}`);p.setAttribute("fill","none");p.setAttribute("stroke","#95a3b8");p.setAttribute("stroke-width","3");$("svg").appendChild(p)})}
function attachNode(el,n){el.querySelector("[contenteditable]").oninput=e=>{n.title=e.target.textContent.trim();save()};el.querySelector(".short").oninput=e=>{n.short=e.target.value;save()};el.querySelector(".del").onclick=async e=>{e.stopPropagation();if(!confirm("Smazat kartu?"))return;let d=ensure();d.nodes=d.nodes.filter(x=>x.id!=n.id);d.edges=d.edges.filter(x=>x.from!=n.id&&x.to!=n.id);current.data=d;await save();renderWork()};el.querySelector(".addChild").onclick=async e=>{e.stopPropagation();let d=ensure(),ch={id:uid(),title:current.type=="pavojk"?"Nová buňka":"Nová stránka",x:n.x+440,y:n.y+80,detail:"",detailImages:[],notes:[],approvals:{karel:false,ivca:false,vlada:false},titleColor:current.type=="pavojk"?"orange":"red"};d.nodes.push(ch);d.edges.push({id:uid(),from:n.id,to:ch.id});await save();renderWork()};el.querySelectorAll(".openDetail").forEach(b=>b.onclick=e=>{e.stopPropagation();openDetail({type:"node",nodeId:n.id})});let f=el.querySelector(".nodeFile");if(f)f.onchange=async e=>{let file=e.target.files[0];if(!file)return;let up=await upload(file,`projects/${current.id}/nodes/${n.id}`);if(!up)return;n.imagePath=up.path;n.imageUrl=up.url;await save();el.querySelector(".imgArea").innerHTML=`<img src="${n.imageUrl}">`;f.value=""};el.querySelector(".noteBtn").onclick=e=>{e.stopPropagation();openNotes(el,n)};let ab=el.querySelector(".apprBtn");if(ab)ab.onclick=e=>{e.stopPropagation();openApprovals(el,n)};el.onpointerdown=e=>{if(e.target.closest("button,input,label,textarea,[contenteditable],.notes,.appr"))return;drag={el,n};off.x=e.clientX-n.x;off.y=e.clientY-n.y;el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(!drag||drag.n.id!=n.id)return;n.x=e.clientX-off.x;n.y=e.clientY-off.y;el.style.left=n.x+"px";el.style.top=n.y+"px";renderEdges()};el.onpointerup=async()=>{if(drag){drag=null;await save()}}}
function openNotes(el,n){el.querySelector(".notes")?.remove();let p=document.createElement("div");p.className="notes";p.innerHTML=`<div class="notesHead"><span>💡 Poznámky</span><button>×</button></div><div class="notesList"></div><div class="notesForm"><input class="ne" value="${session.user.email}"><textarea class="nt" placeholder="Napiš poznámku..."></textarea><button class="primary send">Odeslat poznámku</button></div>`;el.appendChild(p);renderNotes(p,n);p.querySelector(".notesHead button").onclick=()=>p.remove();p.querySelector(".send").onclick=async()=>{let email=p.querySelector(".ne").value.trim(),text=p.querySelector(".nt").value.trim();if(!email||!text)return toast("Vyplň email i poznámku");n.notes=n.notes||[];n.notes.push({id:uid(),email,text,createdAt:new Date().toISOString()});p.querySelector(".nt").value="";await save();renderNotes(p,n);let nb=el.querySelector(".noteBtn");nb.dataset.count=n.notes.length;nb.classList.add("has")}}
function renderNotes(p,n){let l=p.querySelector(".notesList");if(!n.notes?.length){l.innerHTML='<p class="muted" style="text-align:center;margin-top:40px">Zatím žádné poznámky.</p>';return}l.innerHTML=n.notes.map(x=>`<div class="note"><div class="avatar">${esc((x.email||"?")[0].toUpperCase())}</div><div class="bubble"><b>${esc(x.email)} · ${fmt(x.createdAt)}</b><br>${esc(x.text)}</div></div>`).join("")}
function openApprovals(el,n){el.querySelector(".appr")?.remove();let a=document.createElement("div");a.className="appr";a.innerHTML=["karel","ivca","vlada"].map(p=>`<div>${p=="karel"?"Karel":p=="ivca"?"Ivča":"Vláďa"}<br><button class="${n.approvals?.[p]?"active":""}" data-p="${p}">👍</button></div>`).join("");el.appendChild(a);a.querySelectorAll("button").forEach(b=>b.onclick=async e=>{e.stopPropagation();n.approvals=n.approvals||{};n.approvals[b.dataset.p]=!n.approvals[b.dataset.p];await save();renderWork()})}
async function upload(file,folder){let ext=file.name.split(".").pop()||"png",path=`${folder}/${uid()}.${ext}`;let {error}=await supabaseClient.storage.from("images").upload(path,file,{cacheControl:"3600"});if(error){console.warn(error);toast("Nahrání obrázku selhalo");return null}let {data}=await supabaseClient.storage.from("images").createSignedUrl(path,604800);return{path,url:data?.signedUrl||""}}
function target(){let d=current.data||{};if(active?.type=="node")return d.nodes?.find(n=>n.id==active.nodeId);if(active?.type=="calNote")return d.notes?.find(n=>n.id==active.id);if(active?.type=="calDay")return d.dayDetails?.[active.date];if(active?.type=="tlItem"){let r=d.rows?.find(r=>r.id==active.rowId);return r?.items?.find(i=>i.id==active.itemId)}}
function openDetail(a){active=a;let t=target();if(!t)return;$("detailTitle").textContent="Detail – "+(t.title||t.name||"Nová buňka");$("detailText").value=t.detail||"";renderDetailImgs(t);$("detailModal").classList.remove("hidden")}
function renderDetailImgs(t){let imgs=t.detailImages||[];$("detailImgs").innerHTML=imgs.length?imgs.map((im,i)=>`<div class="dimg"><img src="${im.url}"><button data-i="${i}">×</button></div>`).join(""):'<p class="muted" style="text-align:center;padding:24px;border:1px dashed var(--bd);border-radius:16px">Zatím nejsou přidané žádné obrázky.</p>';$("detailImgs").querySelectorAll("img").forEach(im=>im.onclick=()=>{$("bigImg").src=im.src;$("imgModal").classList.remove("hidden")});$("detailImgs").querySelectorAll("button").forEach(b=>b.onclick=async()=>{t.detailImages.splice(+b.dataset.i,1);await save();renderDetailImgs(t)})}
$("detailFile").onchange=async e=>{let t=target(),files=[...e.target.files];if(!t||!files.length)return;t.detailImages=t.detailImages||[];for(let file of files){let up=await upload(file,`projects/${current.id}/details`);if(up){t.detailImages.push(up);renderDetailImgs(t)}}await save();e.target.value=""}
$("saveDetail").onclick=async()=>{let t=target();if(!t)return;t.detail=$("detailText").value;await save();$("detailModal").classList.add("hidden");renderWork()}
$("deleteDetail").onclick=async()=>{if(!confirm("Opravdu smazat?"))return;let d=current.data;if(active.type=="node"){d.nodes=d.nodes.filter(n=>n.id!=active.nodeId);d.edges=d.edges.filter(e=>e.from!=active.nodeId&&e.to!=active.nodeId)}else if(active.type=="calNote")d.notes=d.notes.filter(n=>n.id!=active.id);else if(active.type=="calDay")delete d.dayDetails[active.date];else if(active.type=="tlItem"){let r=d.rows.find(r=>r.id==active.rowId);r.items=r.items.filter(i=>i.id!=active.itemId)}await save();$("detailModal").classList.add("hidden");renderWork()}
$("closeDetail").onclick=()=>$("detailModal").classList.add("hidden");$("closeImg").onclick=()=>{$("imgModal").classList.add("hidden");$("bigImg").src=""}

function renderTimeline(){let d=current.data;$("canvas").innerHTML="";let w=document.createElement("div");w.className="timeline";let days=[...Array(d.days||198)].map((_,i)=>{let x=new Date(d.start);x.setDate(x.getDate()+i);return x});w.innerHTML=`<table class="tl"><thead><tr><th>Časová osa</th>${days.map(x=>`<th>${x.toLocaleDateString("cs-CZ",{day:"2-digit",month:"2-digit"})}</th>`).join("")}</tr></thead><tbody>${(d.rows||[]).map(r=>`<tr data-r="${r.id}"><td><div class="tlTitle"><button class="danger delr">×</button><span contenteditable>${esc(r.name)}</span><button class="addi">✎</button></div></td>${days.map(x=>`<td data-date="${dstr(x)}"></td>`).join("")}</tr>`).join("")}</tbody></table><button class="addRow" style="margin:16px">+ Přidat řádek</button>`;$("canvas").appendChild(w);(d.rows||[]).forEach(r=>(r.items||[]).forEach(it=>{let row=w.querySelector(`tr[data-r="${r.id}"]`),si=days.findIndex(x=>dstr(x)==it.start),ei=days.findIndex(x=>dstr(x)==it.end);if(si<0)return;let cell=row.children[si+1],div=document.createElement("div");div.className=`tlItem tl${it.color||"red"}`;div.style.width=`${Math.max(1,(ei-si+1))*46-6}px`;div.textContent=it.title||r.name;div.ondblclick=()=>openDetail({type:"tlItem",rowId:r.id,itemId:it.id});cell.appendChild(div)}));w.querySelector(".addRow").onclick=async()=>{d.rows.push({id:uid(),name:"Nový řádek",items:[]});await save();renderWork()};w.querySelectorAll("tr[data-r]").forEach(tr=>{let r=d.rows.find(x=>x.id==tr.dataset.r);tr.querySelector("span").oninput=e=>{r.name=e.target.textContent.trim();save()};tr.querySelector(".delr").onclick=async()=>{d.rows=d.rows.filter(x=>x.id!=r.id);await save();renderWork()};tr.querySelector(".addi").onclick=async()=>{r.items.push({id:uid(),title:r.name||"Položka",start:d.start,end:d.start,color:"red",detail:"",detailImages:[]});await save();renderWork()}})}
function calDays(y,m){let f=new Date(y,m,1),fd=(f.getDay()+6)%7,s=new Date(y,m,1-fd);return[...Array(42)].map((_,i)=>{let x=new Date(s);x.setDate(s.getDate()+i);return x})}
function renderCalendar(){let d=current.data,t=new Date();d.notes=d.notes||[];d.dayDetails=d.dayDetails||{};if(typeof d.year!="number")d.year=t.getFullYear();if(typeof d.month!="number")d.month=t.getMonth();$("canvas").innerHTML="";let w=document.createElement("div");w.className="calendar";let days=calDays(d.year,d.month),mn=new Date(d.year,d.month,1).toLocaleDateString("cs-CZ",{month:"long",year:"numeric"});w.innerHTML=`<div class="calTop"><button class="prev">‹</button><button class="next">›</button><h2>${esc(mn)}</h2><button class="today">Dnes</button></div><div class="calGrid">${["Po","Út","St","Čt","Pá","So","Ne"].map(x=>`<div class="wd">${x}</div>`).join("")}${days.map(x=>{let dv=dstr(x),notes=d.notes.filter(n=>n.date==dv);return`<div class="day ${x.getMonth()!=d.month?"other":""}" data-date="${dv}"><div class="dayHead"><b>${x.getDate()}</b><button class="addN">+</button></div>${notes.map(n=>`<div class="calNote" data-id="${n.id}">${esc(n.title||"Nová poznámka")}</div>`).join("")}</div>`}).join("")}</div>`;$("canvas").appendChild(w);w.querySelector(".prev").onclick=async()=>{d.month--;if(d.month<0){d.month=11;d.year--}await save();renderWork()};w.querySelector(".next").onclick=async()=>{d.month++;if(d.month>11){d.month=0;d.year++}await save();renderWork()};w.querySelector(".today").onclick=async()=>{d.year=t.getFullYear();d.month=t.getMonth();await save();renderWork()};w.querySelectorAll(".day").forEach(day=>{let date=day.dataset.date;day.ondblclick=e=>{if(e.target.closest("button,.calNote"))return;if(!d.dayDetails[date])d.dayDetails[date]={title:"Detail dne "+date,detail:"",detailImages:[]};openDetail({type:"calDay",date})};day.querySelector(".addN").onclick=async e=>{e.stopPropagation();let n={id:uid(),date,title:"Nová poznámka",detail:"",detailImages:[]};d.notes.push(n);await save();renderWork();openDetail({type:"calNote",id:n.id})}});w.querySelectorAll(".calNote").forEach(n=>n.ondblclick=e=>{e.stopPropagation();openDetail({type:"calNote",id:n.dataset.id})})}

$("newProject").onclick=()=>{$("projectTitleInput").value="";$("typeModal").classList.remove("hidden")};$("closeType").onclick=()=>$("typeModal").classList.add("hidden");document.querySelectorAll(".typeGrid button").forEach(b=>b.onclick=()=>createProject(b.dataset.type,$("projectTitleInput").value.trim()||"Projekt "+(projects.length+1)));
$("back").onclick=async()=>{await loadProjects();renderProjects();current=null;show("projects")};$("printPdf").onclick=()=>window.print();$("deleteProject").onclick=async()=>{if(!current||!confirm("Smazat projekt?"))return;let {error}=await supabaseClient.from("projects").delete().eq("id",current.id);if(error)return toast("Projekt se nepodařilo smazat");projects=projects.filter(p=>p.id!=current.id);current=null;renderProjects();show("projects")};$("addMain").onclick=async()=>{if(!current)return;if(current.type=="timeline"){current.data.rows.push({id:uid(),name:"Nový řádek",items:[]});await save();return renderWork()}if(current.type=="notesCalendar")return toast("V kalendáři přidej poznámku přes plus v konkrétním dni.");let d=ensure();d.nodes.push({id:uid(),title:current.type=="pavojk"?"Nová buňka":"Nová stránka",x:1000+d.nodes.length*80,y:520+d.nodes.length*60,detail:"",detailImages:[],notes:[],approvals:{karel:false,ivca:false,vlada:false},titleColor:current.type=="pavojk"?"orange":"red"});await save();renderWork()}
async function logout(){await supabaseClient.auth.signOut();session=null;profile=null;projects=[];current=null;show("login")}$("logout").onclick=logout;$("logoutPending").onclick=logout;
$("adminBtn").onclick=async()=>{await loadRequests();show("admin")};$("backAdmin").onclick=()=>show("projects");
async function loadRequests(){let {data,error}=await supabaseClient.from("profiles").select("*").order("created_at",{ascending:false});if(error)return $("requests").innerHTML="<p>Nepodařilo se načíst žádosti.</p>";let p=(data||[]).filter(x=>x.status=="pending");$("requests").innerHTML=p.length?p.map(x=>`<div class="adminRow"><div><b>${esc(x.email)}</b><div class="muted">Čeká · ${fmt(x.created_at)}</div></div><div><button class="primary approve" data-id="${x.id}">Schválit</button><button class="danger reject" data-id="${x.id}">Zamítnout</button></div></div>`).join(""):'<p class="muted">Žádné čekající žádosti.</p>';$("requests").querySelectorAll(".approve").forEach(b=>b.onclick=()=>status(b.dataset.id,"approved"));$("requests").querySelectorAll(".reject").forEach(b=>b.onclick=()=>status(b.dataset.id,"rejected"))}
async function status(id,status){let patch={status};if(status=="approved")patch.approved_at=new Date().toISOString();let {error}=await supabaseClient.from("profiles").update(patch).eq("id",id);if(error)return toast("Změna selhala");toast(status=="approved"?"Uživatel schválen":"Uživatel zamítnut");loadRequests()}
supabaseClient.auth.onAuthStateChange((_e,s)=>session=s);init();
